package io.dicedev.pantry.domain.enums;

public enum ProductValidatorEnum {
    PANTRY_PRODUCT_AMOUNT_GREATER_THAN_ZERO,
    PANTRY_PRODUCT_NAME_MIN_3_LETTERS,
    PANTRY_PRODUCT_NAME_NO_SMALL_LETTER,
    PANTRY_PRODUCT_CATEGORY_NOT_CHOSEN,
}
